[build]
command = "mkdir -p src/environments && echo \"export const environment = { production: true, tmdbApiKey: '${TMDB_API_KEY}', innaZmienna: '${INNA_ZMIENNA}' };\" > src/environments/environment.ts && npm run build"
publish = "dist/todo-list/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
